version: "3"

services:
  protohackers:
    image: 405934267152.dkr.ecr.ca-central-1.amazonaws.com/protohackers:protohackers-latest
    container_name: protohackers
    restart: unless-stopped
    environment:
      - PORT=4269
    ports:
      - 4269:4269
