# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    terraform {
        required_providers {
            aws = {
            source  = "hashicorp/aws"
            version = "~> 4.20.1"
            }
            hcp = {
            version = "~> 0.75.0"
            source  = "hashicorp/hcp"
            }
            helm = {
            version = "~> 2.10.1"
            source  = "hashicorp/helm"
            }
            kubernetes = {
            version = "~> 2.23.0"
            source  = "hashicorp/kubernetes"
            }
            null = {
            source  = "hashicorp/null"
            version = "~> 3.2.1"
            }
            
            vault = {
                source  = "hashicorp/vault"
                version = "~> 3.21.0"
            }
            
            
        }
        required_version = ">= 1.2.2"
    }
