global:
  labels:
    app: cmstate-operator

deployment:
  labels: {}
  annotations: {}
  pod:
    labels: {}
    annotations: {}
    volumes:
      - name: ${cert_secret}
        secret:
          secretName: ${cert_secret}
        mountPath: /tmp/k8s-webhook-server/serving-certs

service:
  labels: {}
  annotations: {}

replicaCount: 1
image:
  repository: public.ecr.aws/x4a1o1q2/cmstate-operator
  tag: cmstate-operator-0.3.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

resources: {}

serviceAccount:
  create: true
  name: "cmstate-operator"

rbac:
  create: true
  role:
    name: cmstate-operator
    rules:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["get", "list", "watch"]
      - apiGroups: ["apps"]
        resources: ["deployments", "statefulsets", "replicasets", "daemonsets"]
        verbs: ["get", "list", "watch"]
      - apiGroups: [""]
        resources: ["configmaps"]
        verbs: ["create", "delete", "update", "get", "list", "watch"]
      - apiGroups: ["cache.spicedelver.me"]
        resources: ["cmstates"]
        verbs: ["create", "delete", "update", "patch", "get", "list", "watch"]
      - apiGroups: ["cache.spicedelver.me"]
        resources: ["cmstates/finalizers"]
        verbs: ["update"]
      - apiGroups: ["cache.spicedelver.me"]
        resources: ["cmstates/status"]
        verbs: ["get", "patch", "update"]
      - apiGroups: ["cache.spicedelver.me"]
        resources: ["cmtemplates"]
        verbs: ["get","list","watch"]
      - apiGroups: ["cache.spicedelver.me"]
        resources: ["cmtemplates/status"]
        verbs: ["get"]

webhook:
  labels: {}
  annotations:
    "cert-manager.io/inject-ca-from-secret": "${ca_secret}"