controller:
  # image:
  #   chroot: true
  # containerSecurityContext:
    # runAsUser: 101
    # allowPrivilegeEscalation: true
    # readOnlyRootFilesystem: false
    # capabilities:
    #   drop:
    #     - ALL
    #   add:
    #     - NET_BIND_SERVICE
    #     - SYS_CHROOT
  config:
    ssl-protocols: TLSv1.3 TLSv1.2
    load-balance: ewma
    allow-snippet-annotations: "true"
    # disable-access-log: "true"
    enable-vts-status: "true"
    error-log-level: "error"
    hsts: "false"
    # large-client-header-buffers: "4 8K"
    # log-format-upstream: "$status $body_bytes_sent $http_referer"
    # server-name-hash-bucket-size: "1024"
    # server-name-hash-max-size: "1024"
    server-tokens: "false"
    worker-processes: "auto"
    proxy-buffering: "on"
    multi-accept: "off"
    proxy-buffer-size: "16k"
    keep-alive: "1"
    keep-alive-requests: "20000"
    # enable-underscores-in-headers: ""
    # proxy-buffers-size: ""
    # proxy-buffers: ""
  # admissionWebhooks:
  #   patch:
  #     podAnnotations:
  #       sidecar.istio.io/inject: "false"
  podAnnotations: {}
  service:
    annotations: {}
    loadBalancerIP: ${load_balancer_main_ip}
      # If you want NLB instead of ELB, enable this!
    externalTrafficPolicy: Local
  replicaCount: 2
  stats:
    enabled: true
  metrics:
    enabled: true
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
  affinity:
    # An example of preferred pod anti-affinity, weight is in the range 1-100
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - 'nginx-ingress'
            - key: app.kubernetes.io/instance
              operator: In
              values:
              - 'nginx-ingress'
            - key: app.kubernetes.io/component
              operator: In
              values:
              - controller
          topologyKey: kubernetes.io/hostname
defaultBackend:
  replicaCount: 3
