# For creating the StorageClass automatically:
storageClass:
  create: false

  parameters:
    server: 192.168.2.113
    share: ${nfs_path}
    volumeName: nfs-subdir-external-provisioner-root

  # Reclaim policy for the main nfs volume
  reclaimPolicy: Retain
  mountOptions:
    - vers=4
    - nolock
  # Set a provisioner name. If unset, a name will be generated.
  # provisionerName:

  # Set StorageClass as the default StorageClass
  # Ignored if storageClass.create is false
  defaultClass: false

  # Set a StorageClass name
  # Ignored if storageClass.create is false
  name: ${storage_class_name}

  # Allow volume to be expanded dynamically
  allowVolumeExpansion: true

  # Set access mode - ReadWriteOnce, ReadOnlyMany or ReadWriteMany
  accessModes: ReadWriteOnce

  # Set volume bindinng mode - Immediate or WaitForFirstConsumer
  volumeBindingMode: Immediate

  # Storage class annotations
  annotations: {}